uml: avoid unnecessary repetition
drupol/nixos-processes pull request #1
Opened 2022-09-15 11:13 UTC by zseri

2022-09-15 11:52 UTC, drupol commented
Hey hi !

Thanks for your proposal.

Your PR proposes to remove the duplicated part as such:

![](https://planttext.com/api/plantuml/png/TLDBRzD04BxxLup49JbKRIKaa2ELXWW14W54M_Kyzexj8UjTiplEG_AFPzP9sgQ4WzVhUNsFaM-ZO92-jV2Tjpx21NpZYi1NWD3rraAWFpr5oUAANOS1Mp1KOM_bdhOojroxbfn0gGU55rLnmwr5Huzif868BRr8MdOakuwWytQNFixbV936PvcmM4hiVjpzdrqsl7bxzUvzUJLyPcdwOj30fc6XOU6T12vwyI45wq2xOOdiH1yQG-QQokfw-B8p0GUTTD8nsfC1v7TzqR8exizVWBKsHu4Meug68g0hcrccPO4wmbH_SWKei5njC1Z8vyP0wLkTDOdJsI7zn7h_cTy7hckTlFXwSwmuOVKy7rIbsZFvsBCrm15K8BaFqtITE3y5vmKcEuhJiIb_H1LH-G3OTS6lqSOzXnDFniebhaX1raoRc-mrtA91LrCy-a_cW9Y0zf2AdVqpDf-FgAGcZdQzJYyfr2a9ui-OUrnHsaPQIwegHjsEDl3R5-1uswtgU2cXTwlBNdU4XQMaCDyRP2Zm6eMzY-D8hc3oILtenzWv_wGXfuLHVASlSeQhr9W_TDQZEU0h6Qwmb9WebLWs1972ciBiMTM97c1t97jnfFaaLK6oMptqhyp-0W00)

The current diagram is:

![](https://planttext.com/api/plantuml/png/bPHlRzD03CRVvrDOuatxOjec8O5I2JOc14WKq3QqrqxY9AQNkt3dz8-K3uylMKPREWIL6ZLtjf-V7rkz2e9UkiR05zww06VmcKi2Lm92sna3ddvs52G9AxOjUcoWe18x8_UqbMl3bMt82kJw8ByN5JRS6BJqm8NK4B2XlKl3bcJN4hJExEBBgJldfNP98Yo68jtNk-Vfalx5oujNh_EB_WDBtMMz7cng5kfld1NFMIVEnyFAqwvV8blHBmr7nINbvMN_SLTuxBNIGSPWJmAGtdLPmwAwtsu1AqqE0Wq6RHeoZpQl5uc6UMe9Opn0XlbgWxw0zBee87UDfi_2V35SFc76b_JUSrLfePjFRyRR0uIfAcX3wiJiNSUc00wWlP1zEuy_PzRDmJg1sOx2_8WaVK0bBvq7R5llrcZ20Aj2-quCeKjSaUQkcJOZ2vSmknrTXhn6Mr5GIQd9Fce1d4AEdps4eVO97_xmugGVVnVu3rzY4fb0m_b4Vkn191ry8ftrY4csuF8VHgExeQAZorGyDveZnNH9lefQ8Ex4IasB6NSmBcECoePMBMtWXyl0yhPTLU5SV6TNvvrk9cQ68dawUbAGvpKAEpiEFixqlQv1DvoTiYpELmE3k3QPse_rlhV6OV6ehp1SOYuX8kMOrmI1_9hyudTN1_q0smdsRC9yQbL5aYjzw7zHyWi0) has 
has indeed two similar parts that are almost the same.

In the beginning, I also tried to remove the duplicated parts, but while doing it, I noticed that they are actually different.
The first part "Trigger CI" and then "Add commit(s)", while the second one "Add commit(s)" and then "Trigger CI". This is two different things.

I'm not the expert here and I do not close the door, leaving this PR open to gather some feedback from other people and we'll merge it eventually.

2022-09-15 12:03 UTC, drupol commented
I made some local tests and I'm ok to merge this PR, but you would need to add an extra step.

Basically, you just need to add `backward :Add commit(s)` before the last `repeat while...` and it will be ok.

Do you want to make the changes?

2022-09-15 12:08 UTC, drupol requested changes
I added a minor change that makes your PR valid.

Maybe a reorganisation of the swimlanes as seen in the screenshot I posted and we're good to go.

2022-09-15 12:08 UTC, drupol commented on src/life-of-a-pr.plantuml
> +  repeat while (Changes requested?) is (yes) not (no)
```suggestion
  |Contributor|
  backward :Add commit(s);
  repeat while (Changes requested?) is (yes) not (no)
```

2022-09-15 16:01 UTC, merged

2022-09-15 16:01 UTC, drupol commented
Thanks for your contribution.

2022-09-15 21:41 UTC, zseri commented
I think another step is missing, because usually long lists of changes are squashed before stuff gets merged.

2022-09-16 04:41 UTC, drupol commented
> I think another step is missing, because usually long lists of changes are squashed before stuff gets merged.

A new PR ? :)

2022-09-16 06:18 UTC, drupol commented
> I think another step is missing, because usually long lists of changes are squashed before stuff gets merged.

After giving a second though, I think this is part of the "Waiting for approvals" part of the workflow.